# Generated by Django 4.2 on 2023-11-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.CharField(max_length=50, verbose_name='Primeiro Valor')),
                ('num2', models.CharField(max_length=50, verbose_name='Segundo Valor')),
                ('op', models.CharField(choices=[('ad', 'Adição'), ('sub', 'Subtração'), ('mult', 'Multiplicação'), ('div', 'Divisão'), ('exp', 'Exponenciação')], max_length=50, verbose_name='Tipo de operação')),
                ('result', models.CharField(max_length=50, verbose_name='Resultado')),
                ('log', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
        ),
    ]
